
[development]
address = "0.0.0.0"
port = 80
workers = 8
log = "normal"
limits = { forms = 32768 }
template_dir = "templates"

[staging]
address = "0.0.0.0"
port = 80
workers = 8
log = "normal"
limits = { forms = 32768 }
template_dir = "templates"

[production]
address = "0.0.0.0"
port = 80
workers = 8
log = "critical"
limits = { forms = 32768 }
template_dir = "templates"
