# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'boood' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for boood

  target 'booodTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'booodUITests' do
    # Pods for testing
  end

end
